FROM {{ item.image }}

RUN yum makecache fast \
 && yum install -y epel-release \
 && yum install -y python python-pip sudo yum-plugin-ovl bash docker iptables net-tools \
 && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
 && yum clean all

RUN pip install docker-py
RUN echo DOCKER_STORAGE_OPTIONS=" --storage-driver=vfs" > /etc/sysconfig/docker-storage && \
    echo STORAGE_DRIVER="" > /etc/sysconfig/docker-storage-setup && \
    sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config
RUN systemctl enable docker

VOLUME /var/lib/docker
